-- 这些字段已在数据库中存在，此处设为空以防止重复执行报错
-- ALTER TABLE platform_accounts ADD COLUMN authToken TEXT;
-- ALTER TABLE platform_accounts ADD COLUMN isVerified INTEGER DEFAULT 0;
-- ALTER TABLE platform_accounts ADD COLUMN lastVerifiedAt INTEGER;
